/* ── HELP CENTRE DATA (ENGLISH) ── */
window.UI_STRINGS = {
  helpCentre: "Help Centre",
  searchGuides: "Search guides...",
  resources: "Resources",
  tutorials: "Tutorials",
  tryProduct: "Try Product",
  howCanWeHelp: "How can we <span>help you?</span>",
  exploreGuides: "Explore our guides, video tutorials, and technical papers to master document intelligence.",
  searchPlaceholder: "Search for answers, guides, features...",
  browseByTopic: "Browse by Topic",
  videoTutorials: "Video Tutorials",
  resourcesAndPapers: "Resources & White Papers",
  stillNeedHelp: "Still need help?",
  supportTeamAvailability: "Our support team is available 24/7 for premium enterprise users.",
  contactSupport: "Contact Support",
  footerDesc: "AI-powered document intelligence for enterprise knowledge management. Transform your static documents into interactive knowledge assets.",
  solution: "Solution", support: "Support", legal: "Legal",
  features: "Features", securityTitle: "Security", pricing: "Pricing", enterprise: "Enterprise",
  apiDocs: "API Docs", systemStatus: "System Status", contact: "Contact",
  privacyPolicy: "Privacy Policy", termsOfService: "Terms of Service",
  cookiePolicy: "Cookie Policy", allRightsReserved: "All rights reserved.",
  builtWithPrecision: "Built with precision for premium enterprise users.",
  browseAllSupport: "Browse All Support", moreArticles: "more", articlesLabel: "articles",
  readTime: "min read", updated: "Updated", previous: "Previous", next: "Next",
  home: "Home", noResults: "No results found."
};

window.CATS = [
  { id: 'getting-started', title: 'Getting Started', bg: '#dbeafe', fg: '#1B2571',
    desc: 'Learn what Doc-Scribe.ai is and how it transforms your document workflow.',
    arts: ['what-is', 'how-it-works'],
    icon: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M12 2C12 2 6 6 6 12c0 2 1 4 2 5l4 2 4-2c1-1 2-3 2-5 0-6-6-10-6-10z"/><circle cx="12" cy="12" r="2"/></svg>' },
  { id: 'doc-management', title: 'Document Management', bg: '#d1fae5', fg: '#047857',
    desc: 'Upload, organize, tag, and manage your documents effectively.',
    arts: ['upload', 'mybox-vs-cat', 'create-cat', 'collections', 'metadata'],
    icon: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M3 7a2 2 0 0 1 2-2h3.5l2 2H19a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V7z"/><path d="M12 11v4M10 13h4"/></svg>' },
  { id: 'ai-features', title: 'AI Features', bg: '#fce7f3', fg: '#be185d',
    desc: 'Interact with your documents using powerful AI modes and chat.',
    arts: ['chat-ai', 'ai-modes', 'cross-doc', 'export-ai'],
    icon: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><rect x="6" y="6" width="12" height="12" rx="2"/><path d="M6 10H3M6 14H3M18 10h3M18 14h3M10 6V3M14 6V3M10 18v3M14 18v3"/><circle cx="12" cy="12" r="2"/></svg>' },
  { id: 'sharing', title: 'Sharing & Collaboration', bg: '#fef3c7', fg: '#b45309',
    desc: 'Share documents and collaborate with your team securely.',
    arts: ['sharing'],
    icon: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="18" cy="5" r="2.5"/><circle cx="6" cy="12" r="2.5"/><circle cx="18" cy="19" r="2.5"/><path d="M8.4 10.8l7.2-4.1M8.4 13.2l7.2 4.1"/></svg>' },
  { id: 'account', title: 'Account & Settings', bg: '#ede9fe', fg: '#6d28d9',
    desc: 'Manage your profile, roles, notifications and preferences.',
    arts: ['user-roles', 'account-settings', 'notifications'],
    icon: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="12" cy="8" r="3.5"/><path d="M5 20c0-3.5 3.1-6 7-6s7 2.5 7 6"/></svg>' },
  { id: 'troubleshooting', title: 'Troubleshooting', bg: '#fee2e2', fg: '#dc2626',
    desc: 'Find solutions to common issues and get back on track quickly.',
    arts: ['troubleshooting', 'data-security'],
    icon: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M14.7 6.3a1 1 0 0 0 0 1.4l1.6 1.6a1 1 0 0 0 1.4 0l3.77-3.77a6 6 0 0 1-7.94 7.94l-6.91 6.91a2.12 2.12 0 0 1-3-3l6.91-6.91a6 6 0 0 1 7.94-7.94l-3.76 3.76z"/></svg>' }
];

window.ARTS = {
  'what-is': { cat: 'getting-started', title: 'What is Doc-Scribe.ai', exc: 'An AI-powered document intelligence platform for enterprise knowledge management.', body: '<p>Doc-Scribe.ai is an <strong>AI-powered document intelligence platform</strong> that helps organizations manage, understand, and extract knowledge from their documents.</p><h2>The Problem It Solves</h2><p>Modern organizations generate thousands of documents &mdash; reports, policies, meeting minutes, contracts, and project records. Finding the right information often requires employees to manually search through files, making the process slow and inefficient.</p><h2>The Solution</h2><p>Instead of manually searching, users can <strong>ask questions directly to their documents</strong> using conversational AI. The system retrieves relevant information, summarizes key insights, and delivers accurate responses in seconds.</p><div class="tip"><strong>In simple terms:</strong> You no longer search your documents &mdash; you ask them.</div><h2>Who Is It For?</h2><ul><li>Organizations managing large volumes of documents</li><li>Teams needing fast, accurate answers from internal records</li><li>Enterprises requiring a secure, private AI environment</li></ul>' },

  'how-it-works': { cat: 'getting-started', title: 'How Doc-Scribe.ai Works', exc: 'Combines a Document Management System with a private AI engine built for enterprise.', body: '<p>Doc-Scribe.ai combines a <strong>Document Management System (DMS)</strong> with a private AI engine designed specifically for enterprise documents.</p><h2>Core Capabilities</h2><ul><li>Store and organize documents securely</li><li>Search documents using natural language</li><li>Analyze documents with AI</li><li>Extract key information automatically</li><li>Generate summaries and insights instantly</li></ul><img src="images/image1.png" alt="Doc-Scribe.ai Core Capabilities" class="screenshot"><h2>Secure Enterprise Platform</h2><ul><li>Private AI environment &mdash; your data never leaves your organization</li><li>Role-based access control</li><li>Secure document sharing</li><li>Permission-based data access</li></ul><h2>Multi-Document Interaction</h2><p>Users can ask questions across <strong>multiple documents at the same time</strong>, finding insights from large document collections instantly.</p><div class="tip"><strong>How it works:</strong> The system reads your documents, builds a private knowledge index, and allows you to interact through a chat interface &mdash; all within a secure, private environment.</div>' },

  'upload': { cat: 'doc-management', title: 'Upload Your First Document', exc: 'Step-by-step guide to uploading and processing your first document.', body: '<p>Uploading a document is the first step to using Doc-Scribe.ai. Once uploaded, the AI automatically processes and indexes your document so it is ready to query.</p><h2>Steps to Upload</h2><ol><li>Click <strong>Upload</strong> from the navigation menu.</li><li>Select a file from your computer.</li><li>Choose the destination: <strong>My Box</strong> (private) or a <strong>Category</strong> (shared).</li><li>Click <strong>Upload Now</strong>.</li></ol><img src="images/image2.png" alt="Doc-Scribe.ai Upload" class="screenshot"><h2>What Happens After Upload</h2><ul><li>Processes the document</li><li>Extracts text content</li><li>Indexes the content for AI search</li><li>Makes the document available for Chat AI</li></ul><div class="tip"><strong>Tip:</strong> Documents are usually ready within seconds. For large files, allow a moment for processing to complete.</div>' },

  'mybox-vs-cat': { cat: 'doc-management', title: 'My Box vs Categories', exc: 'Understand the two storage environments and when to use each.', body: '<p>Doc-Scribe.ai provides two document storage environments.</p><h2>My Box</h2><p>My Box is your <strong>personal document space</strong>. Files stored here are private by default &mdash; visible only to you.</p><h2>Categories</h2><p>Categories are <strong>shared departmental folders</strong>. Documents can be accessed by users within the same department.</p><h2>Quick Comparison</h2><table><thead><tr><th>Feature</th><th>My Box</th><th>Categories</th></tr></thead><tbody><tr><td>Visibility</td><td>Private (you only)</td><td>Shared (department)</td></tr><tr><td>Best for</td><td>Drafts, personal files</td><td>Team collaboration</td></tr><tr><td>Access control</td><td>You control</td><td>Admin + role-based</td></tr></tbody></table><div class="tip"><strong>Tip:</strong> Use My Box for anything you are not ready to share. Move to a Category when it is ready for the team.</div>' },

  'create-cat': { cat: 'doc-management', title: 'Creating Categories', exc: 'Learn how to create and manage departmental document categories.', body: '<p>Categories help organize documents within departments and make them accessible to the right team members.</p><h2>Steps to Create a Category</h2><ol><li>Click <strong>Manage Categories</strong> from the navigation menu.</li><li>Ensure the <strong>Main Tab</strong> is selected.</li><li>Enter a <strong>Category Name</strong> (e.g., Quotations).</li><li>Choose an icon and color (optional).</li><li>Click <strong>Create</strong>.</li></ol><div class="tip"><strong>Best practice:</strong> Name categories after departments or document types to make navigation intuitive for all team members.</div>' },

  'collections': { cat: 'doc-management', title: 'Using Collections', exc: 'Group documents from different categories into one virtual workspace.', body: '<p>Collections allow you to <strong>group documents from different categories</strong> into a single virtual workspace. The originals remain in their categories.</p><h2>Creating a Collection</h2><ol><li>Click <strong>Collections</strong> in the navigation.</li><li>Click <strong>New Collection</strong>.</li><li>Enter a collection name.</li><li>Click <strong>Create</strong>.</li></ol><div class="tip"><strong>Tip:</strong> When you run AI Search on a collection, the AI analyses all documents together &mdash; great for cross-document insights.</div>' },

  'metadata': { cat: 'doc-management', title: 'Metadata and Tagging', exc: 'Attach metadata fields to documents to improve search accuracy.', body: '<p>Metadata allows you to <strong>attach additional information</strong> to documents, making them easier to search and helping the AI understand content more accurately.</p><h2>Example &mdash; Invoice Metadata</h2><ul><li>Invoice Number</li><li>Invoice Date</li><li>Supplier</li><li>Total Amount</li></ul><h2>Creating a File Tag</h2><ol><li>Click <strong>Manage File Tags</strong>.</li><li>Select <strong>Create New File Tag</strong>.</li><li>Enter a tag name (e.g., Invoice).</li><li>Add metadata fields such as Invoice Number, Invoice Date.</li><li>Click <strong>Create New File Tag</strong>.</li></ol><div class="tip"><strong>Pro tip:</strong> Well-tagged documents surface more accurate AI responses and make retrieval significantly faster.</div>' },

  'chat-ai': { cat: 'ai-features', title: 'Interacting with Chat AI', exc: 'Ask questions directly to your documents using natural language.', body: '<p>Chat AI allows users to <strong>interact directly with documents</strong> using natural language. Instead of reading the entire document, you simply ask questions.</p><h2>Steps to Use Chat AI</h2><ol><li>Navigate to the document you want to analyze.</li><li>Select the document.</li><li>Click <strong>AI Search</strong>.</li><li>Enter your question in the Chat AI window.</li></ol><h2>Example Queries</h2><ul><li>"Summarize this document"</li><li>"What is the total quotation value?"</li><li>"List all suppliers mentioned"</li><li>"Extract invoice numbers"</li></ul><div class="tip"><strong>Pro tip:</strong> Start broad ("Summarize this") then drill down for the most precise answers.</div>' },

  'ai-modes': { cat: 'ai-features', title: 'Understanding AI Modes', exc: 'Six specialized AI modes designed for different types of document analysis.', body: '<p>Doc-Scribe provides several <strong>AI modes</strong> designed for different types of document analysis.</p><div class="mode-cards"><div class="mode-card"><div class="mode-card-head"><div class="mode-ico" style="background:#dbeafe;color:#1B2571">GQ</div><h4>General Query</h4></div><p>Used for everyday questions and general summaries.</p><div class="mode-ex">Example: "Summarize this document."</div></div><div class="mode-card"><div class="mode-card-head"><div class="mode-ico" style="background:#d1fae5;color:#065f46">VZ</div><h4>Visualizer</h4></div><p>Creates charts, diagrams, and visual summaries from document data.</p></div><div class="mode-card"><div class="mode-card-head"><div class="mode-ico" style="background:#fce7f3;color:#9d174d">AN</div><h4>Analyst</h4></div><p>Performs deeper analysis and identifies patterns or inconsistencies.</p><div class="mode-ex">Example: "Compare supplier quotations."</div></div><div class="mode-card"><div class="mode-card-head"><div class="mode-ico" style="background:#fef3c7;color:#92400e">RV</div><h4>Reviewer</h4></div><p>Checks documents for errors, missing information, or inconsistencies.</p></div><div class="mode-card"><div class="mode-card-head"><div class="mode-ico" style="background:#ede9fe;color:#4c1d95">TR</div><h4>Transcript</h4></div><p>Analyzes meeting transcripts and extracts key discussions, decisions, and tasks.</p></div><div class="mode-card"><div class="mode-card-head"><div class="mode-ico" style="background:#fee2e2;color:#991b1b">EX</div><h4>Extractor</h4></div><p>Extracts structured data from documents such as invoices or reports for export to ERP or Excel.</p></div></div><div class="tip"><strong>Choosing the right mode:</strong> Use General Query for quick questions, Analyst for complex comparisons, and Extractor when you need structured data you can download.</div>' },

  'cross-doc': { cat: 'ai-features', title: 'Cross-Document Analysis', exc: 'Ask questions across multiple documents simultaneously.', body: '<p>Cross-document analysis lets you ask questions <strong>across multiple documents at the same time</strong>.</p><h2>How to Use It</h2><ol><li>Create a <strong>Collection</strong> with the relevant documents.</li><li>Open the collection.</li><li>Click <strong>AI Search</strong> &mdash; the AI will search across all documents.</li><li>Enter your question.</li></ol><h2>Example Queries</h2><ul><li>"Which supplier has the lowest price across all quotations?"</li><li>"Summarize the key decisions from all meeting minutes this quarter"</li><li>"Are there inconsistencies between the contract and the scope of work?"</li></ul><div class="tip"><strong>Tip:</strong> Keep collections focused on a single topic for the best cross-document results.</div>' },

  'export-ai': { cat: 'ai-features', title: 'Exporting AI Results', exc: 'Export structured data extracted by AI into Excel or your ERP system.', body: '<p>AI results &mdash; especially from <strong>Extractor Mode</strong> &mdash; can be exported into structured formats.</p><h2>Supported Export Formats</h2><ul><li>Excel (.xlsx)</li><li>CSV</li><li>JSON (for ERP/API integration)</li></ul><h2>How to Export</h2><ol><li>Run an <strong>Extractor Mode</strong> query on your document(s).</li><li>Review the extracted data in the results panel.</li><li>Click <strong>Export</strong> and choose your format.</li><li>The file will download or be sent to your configured integration.</li></ol><div class="tip"><strong>Tip:</strong> Use Extractor mode and export to Excel when you need to feed AI results into finance or operations systems.</div>' },

  'sharing': { cat: 'sharing', title: 'Sharing Documents', exc: 'Share documents securely with users across departments.', body: '<p>Documents can be shared with other users or departments with controlled permission levels.</p><h2>Steps to Share a Document</h2><ol><li>Open the document.</li><li>Click <strong>Share</strong>.</li><li>Select a user from the same or another department.</li><li>Choose a permission level.</li></ol><h2>Permission Levels</h2><table><thead><tr><th>Permission</th><th>Description</th></tr></thead><tbody><tr><td><strong>Can View</strong></td><td>User can view and interact with the document using Chat AI</td></tr><tr><td><strong>Can Download</strong></td><td>User can view and download the document</td></tr></tbody></table><div class="tip"><strong>Principle of least privilege:</strong> Use "Can View" for most collaboration needs. Only grant download access when genuinely required.</div>' },

  'user-roles': { cat: 'account', title: 'User Roles and Permissions', exc: 'Understand the different user roles and what access each provides.', body: '<p>Doc-Scribe.ai uses <strong>role-based access control</strong> to ensure users only access what they need.</p><h2>Available Roles</h2><table><thead><tr><th>Role</th><th>Description</th></tr></thead><tbody><tr><td><strong>Administrator</strong></td><td>Full access &mdash; manage users, categories, system settings</td></tr><tr><td><strong>Manager</strong></td><td>Manage documents and users within their department</td></tr><tr><td><strong>User</strong></td><td>Upload, view, and interact with permitted documents</td></tr><tr><td><strong>Read Only</strong></td><td>View documents only &mdash; no upload or edit access</td></tr></tbody></table><div class="tip"><strong>Best practice:</strong> Assign the most restrictive role that still allows the user to do their job.</div>' },

  'account-settings': { cat: 'account', title: 'Account and Profile Settings', exc: 'Update your profile, password, and language preferences.', body: '<p>You can manage your account details from the <strong>Profile Settings</strong> page.</p><h2>Updating Your Profile</h2><ol><li>Click your name or avatar in the top-right corner.</li><li>Select <strong>Profile Settings</strong>.</li><li>Update your name, email, or profile picture.</li><li>Click <strong>Save Changes</strong>.</li></ol><h2>Changing Your Password</h2><ol><li>Go to <strong>Profile Settings &rarr; Security</strong>.</li><li>Enter your current password.</li><li>Enter and confirm your new password.</li><li>Click <strong>Update Password</strong>.</li></ol><div class="tip"><strong>Security tip:</strong> Use a strong, unique password and enable two-factor authentication if available.</div>' },

  'notifications': { cat: 'account', title: 'Notification Settings', exc: 'Control which alerts and emails you receive from Doc-Scribe.ai.', body: '<p>You can control which notifications Doc-Scribe.ai sends you.</p><h2>Configuring Notifications</h2><ol><li>Go to <strong>Settings &rarr; Notifications</strong>.</li><li>Toggle each notification type on or off.</li><li>Choose delivery method: In-App, Email, or Both.</li><li>Click <strong>Save</strong>.</li></ol><h2>Available Notifications</h2><table><thead><tr><th>Notification</th><th>Triggered When</th></tr></thead><tbody><tr><td>Document Shared</td><td>Someone shares a document with you</td></tr><tr><td>Processing Complete</td><td>An uploaded document has finished indexing</td></tr><tr><td>AI Export Ready</td><td>Your data export is ready to download</td></tr><tr><td>Access Granted</td><td>Your role or permissions are updated</td></tr></tbody></table><div class="tip"><strong>Tip:</strong> Keep "Document Shared" and "Processing Complete" notifications on &mdash; these are the most actionable alerts.</div>' },

  'troubleshooting': { cat: 'troubleshooting', title: 'Troubleshooting Common Issues', exc: 'Find quick fixes for the most common issues in Doc-Scribe.ai.', body: '<p>Find solutions to common issues below. If your problem is not listed, please contact our support team.</p><div class="ts-item"><div class="ts-q" onclick="toggleTs(this)">Cannot Upload Document<svg class="ts-ch" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="m6 9 6 6 6-6"/></svg></div><div class="ts-a"><div class="ts-a-inner">&bull; File size is within permitted limits<br>&bull; Internet connection is stable<br>&bull; File format is supported (PDF, DOCX, XLSX, PPTX, TXT)</div></div></div><div class="ts-item"><div class="ts-q" onclick="toggleTs(this)">AI Search Not Working<svg class="ts-ch" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="m6 9 6 6 6-6"/></svg></div><div class="ts-a"><div class="ts-a-inner">&bull; A document is selected before starting AI Search<br>&bull; The document has finished processing<br>&bull; Try refreshing the page</div></div></div><div class="ts-item"><div class="ts-q" onclick="toggleTs(this)">Cannot Access Shared Document<svg class="ts-ch" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="m6 9 6 6 6-6"/></svg></div><div class="ts-a"><div class="ts-a-inner">&bull; The document was shared directly with your account<br>&bull; Check your "Shared With Me" section<br>&bull; Contact the document owner to re-share if needed</div></div></div><div class="ts-item"><div class="ts-q" onclick="toggleTs(this)">Metadata Not Appearing<svg class="ts-ch" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="m6 9 6 6 6-6"/></svg></div><div class="ts-a"><div class="ts-a-inner">&bull; Refresh the page<br>&bull; Ensure the correct File Tag has been applied<br>&bull; Check all required fields were filled in and saved</div></div></div>' },

  'data-security': { cat: 'troubleshooting', title: 'Data Privacy and Security', exc: 'How Doc-Scribe.ai protects your enterprise data and documents.', body: '<p>Doc-Scribe.ai is built with enterprise security as a core principle.</p><h2>Key Security Features</h2><ul><li><strong>Private AI Environment</strong> &mdash; your documents never leave your private instance</li><li><strong>Role-Based Access Control</strong> &mdash; users only see what they are permitted to see</li><li><strong>Encrypted Storage</strong> &mdash; documents are encrypted at rest and in transit</li><li><strong>Audit Logs</strong> &mdash; all document access and actions are logged</li><li><strong>No Public Cloud AI</strong> &mdash; your data is not sent to public AI models</li></ul><h2>Security FAQ</h2><table><thead><tr><th>Question</th><th>Answer</th></tr></thead><tbody><tr><td>Is my data used to train AI models?</td><td>No. Your data is never used for model training.</td></tr><tr><td>Can other organizations see my documents?</td><td>No. Each deployment is completely isolated.</td></tr><tr><td>Is data encrypted?</td><td>Yes &mdash; at rest (AES-256) and in transit (TLS 1.3).</td></tr></tbody></table><div class="tip"><strong>Note:</strong> For compliance queries (GDPR, PDPA), please contact your account administrator or the Doc-Scribe.ai team directly.</div>' }
};

window.VIDEOS = [
  { id: 'UmLDcJ7pvK4', label: 'Tutorial — Beginner', title: 'Getting Started with Doc-Scribe.ai', desc: 'A complete walkthrough of uploading documents, using Chat AI, and organizing your workspace.', thumb: 'https://img.youtube.com/vi/UmLDcJ7pvK4/maxresdefault.jpg', url: 'https://youtu.be/UmLDcJ7pvK4' },
  { id: 'WtNTT6OnOyk', label: 'Tutorial — Intermediate', title: 'Mastering AI Modes & Analysis', desc: 'Explore all six AI modes and learn how to get the most from cross-document analysis.', thumb: 'https://img.youtube.com/vi/WtNTT6OnOyk/maxresdefault.jpg', url: 'https://youtu.be/WtNTT6OnOyk' }
];

window.PAPERS = [
  { tag: 'White Paper', title: 'The Future of Document Intelligence in Enterprise Organizations', desc: 'How AI-powered document management is transforming knowledge work and unlocking trapped organizational knowledge.', file: 'docs/Doc-Scribe_Security_Whitepaper.pdf' },
  { tag: 'Technical Guide', title: 'AI-Powered Document Processing: Architecture & Security', desc: 'A deep dive into Doc-Scribe.ai private AI architecture, data security model, and deployment options for enterprise environments.', file: 'docs/Use-Cases-for-Vertical-Industries.pdf' }
];
