// Admin Portal — 简体中文
// 在 ../data-zh.js 之后加载；仅覆盖 window.CATS 和 window.ARTS。

window.CATS = [
  { id: 'user-management', title: '用户管理', bg: '#eff6ff', fg: '#1d4ed8', desc: '邀请、管理和移除组织中的用户。', arts: ['admin-add-user', 'admin-roles', 'admin-deactivate', 'admin-reset-password'], icon: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M23 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/></svg>' },
  { id: 'permissions', title: '权限与角色', bg: '#f0fdf4', fg: '#15803d', desc: '配置每个用户角色可以访问和执行的操作。', arts: ['admin-perm-overview', 'admin-perm-category'], icon: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><rect x="3" y="11" width="18" height="11" rx="2"/><path d="M7 11V7a5 5 0 0 1 10 0v4"/></svg>' },
  { id: 'system-config', title: '系统配置', bg: '#fff7ed', fg: '#c2410c', desc: '管理平台设置、文件标签和组织偏好。', arts: ['admin-settings'], icon: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M12 20h9"/><path d="M16.5 3.5a2.121 2.121 0 0 1 3 3L7 19l-4 1 1-4 12.5-12.5z"/></svg>' },
  { id: 'audit-logs', title: '审计与活动日志', bg: '#fef2f2', fg: '#b91c1c', desc: '监控用户活动并生成合规报告。', arts: ['admin-audit-view', 'admin-audit-export'], icon: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="16" y1="13" x2="8" y2="13"/><line x1="16" y1="17" x2="8" y2="17"/><polyline points="10 9 9 9 8 9"/></svg>' },
];

window.ARTS = {
  'admin-add-user': { cat: 'user-management', title: '邀请用户和创建部门', exc: '如何邀请新用户和在组织中创建部门。', body: '<p>进入管理员模式后，从左侧边栏导航到<strong>用户与部门</strong>。顶部有两个标签：</p><ul><li><strong>用户</strong> &mdash;&mdash; 显示系统中所有已注册的用户</li><li><strong>部门</strong> &mdash;&mdash; 显示您组织中创建的所有部门</li></ul><h2>邀请新用户</h2><ol><li>点击用户标签右上角的<strong>邀请用户</strong>按钮。</li><li>将出现一个弹窗。填写以下字段：<ul><li><strong>全名</strong>（必填）&mdash;&mdash; 输入用户的全名。</li><li><strong>电子邮件地址</strong>（必填）&mdash;&mdash; 输入用户的工作邮箱。</li><li><strong>职位</strong>（选填）&mdash;&mdash; 例如：软件工程师。</li></ul></li><li>配置访问设置：<ul><li><strong>使用现有用户</strong> &mdash;&mdash; 如果此人在其他工作区已有账户，请勾选此项。</li><li><strong>全局访问</strong> &mdash;&mdash; 勾选此项以允许用户查看组织内所有部门、分类和文件。</li></ul></li><li>设置<strong>角色</strong> &mdash;&mdash; 从下拉菜单中选择<strong>用户</strong>或<strong>管理员</strong>。</li><li>选择用户所属的<strong>部门</strong>。</li><li>使用滑块调整<strong>每月令牌限额</strong>。默认值为 500，最大值为 10,000。</li><li>在<strong>安全与访问配置</strong>下，如果希望此用户能够创建、编辑和删除文件分类，请勾选<strong>管理分类</strong>。</li><li>点击<strong>发送邀请</strong>以邀请用户。</li></ol><div class="tip"><strong>注意：</strong>弹窗顶部的席位计数器显示当前使用情况，例如 3 / 5。不能邀请超过您计划允许数量的用户。</div><img src="../images/invite user.png" alt="邀请用户" class="screenshot"><p class="screenshot-caption">邀请用户 &mdash;&mdash; 填写用户详情、设置角色和部门</p><div class="tip"><strong>注意：</strong>受邀用户将收到设置账户的电子邮件。</div><div class="warning"><strong>⚠️ 重要：</strong>电子邮件地址必须有效。账户仅在用户点击电子邮件中的验证链接后才会创建。地址错误将导致邀请失败。</div><h2>创建新部门</h2><ol><li>点击部门标签右上角的<strong>+ 创建部门</strong>按钮。</li><li>将出现一个弹窗。填写以下字段：<ul><li><strong>部门名称</strong>（必填）&mdash;&mdash; 输入部门名称，例如工程或人力资源。</li><li><strong>描述</strong>（选填）&mdash;&mdash; 添加部门职能的简短说明。</li></ul></li><li>在<strong>部门经理</strong>下，选择以下之一：<ul><li><strong>现有用户</strong> &mdash;&mdash; 选择系统中已有账户的经理。</li><li><strong>邀请新成员</strong> &mdash;&mdash; 输入经理的姓名和邮箱以发送邀请。</li></ul></li><li>点击<strong>创建部门</strong>保存。</li></ol><img src="../images/invite department.png" alt="创建部门" class="screenshot"><p class="screenshot-caption">创建部门 &mdash;&mdash; 设置名称、描述并分配经理</p><div class="tip"><strong>注意：</strong>部门名称和部门经理是必填字段。创建部门时必须指定经理。</div>' },
  'admin-roles': { cat: 'user-management', title: '分配用户角色', exc: '如何更改用户在平台中的角色。', body: '<p>用户角色决定其可执行的操作，管理员可随时更改。</p><h2>可用角色</h2><table><thead><tr><th>角色</th><th>描述</th></tr></thead><tbody><tr><td><strong>管理员</strong></td><td>完整控制 —— 用户、分类、设置、审计日志。</td></tr><tr><td><strong>部门管理员</strong></td><td>可创建和管理分类；不能管理用户或系统设置。</td></tr><tr><td><strong>用户</strong></td><td>可上传、整理并对可访问文档运行 AI 搜索。</td></tr><tr><td><strong>只读</strong></td><td>只能查看和对共享文档使用 AI 搜索。</td></tr></tbody></table><h2>更改角色</h2><p>点击左侧导航面板中的<strong>用户与部门</strong>。根据需要更改的内容，有两种方式可以更新角色。</p><h3>更改用户角色</h3><ol><li>进入<strong>用户</strong>标签。</li><li>找到该用户，点击操作列中的<strong>三点图标（&hellip;）</strong>。</li><li>点击<strong>编辑</strong>。</li><li>将角色更改为<strong>用户</strong>或<strong>租户管理员</strong>并保存。</li></ol><h3>更改部门经理</h3><ol><li>进入<strong>部门</strong>标签。</li><li>找到该部门，点击操作列中的<strong>三点图标（&hellip;）</strong>。</li><li>点击<strong>编辑部门</strong>。</li><li>将<strong>部门经理</strong>字段更新为其他用户并保存。</li></ol>' },
  'admin-deactivate': { cat: 'user-management', title: '停用和移除用户', exc: '如何暂停或永久移除组织中的用户。', body: '<p>当用户离开或需要暂停访问时，您可以停用或移除其账户。</p><h2>停用用户（推荐）</h2><p>停用暂停访问同时保留所有文档和历史记录，可随时重新激活。</p><ol><li>进入<strong>用户与部门</strong>。</li><li>找到该用户，点击操作列中的<strong>三点图标（&hellip;）</strong>。</li><li>点击<strong>停用用户</strong>。</li><li>在确认框中输入 <strong>FREEZE</strong> 并确认。</li></ol><h2>永久移除用户</h2><p>永久移除将删除账户，My Box 中的文档将被归档。</p><ol><li>进入<strong>用户与部门</strong>。</li><li>找到该用户，点击操作列中的<strong>三点图标（&hellip;）</strong>。</li><li>点击<strong>删除用户</strong>。</li><li>在确认框中输入 <strong>DELETE</strong> 并确认。</li></ol><div class="tip"><strong>注意：</strong>永久移除无法撤销。建议使用停用，除非出于合规原因需要清除数据。</div>' },
  'admin-perm-overview': { cat: 'permissions', title: '权限概述', exc: '每个用户角色能做和不能做的事情的完整分解。', body: '<p>下表总结了平台各功能的权限。</p><table><thead><tr><th>功能</th><th>管理员</th><th>分类管理员</th><th>标准</th><th>只读</th></tr></thead><tbody><tr><td>上传文档</td><td>&#10003;</td><td>&#10003;</td><td>&#10003;</td><td>&#10007;</td></tr><tr><td>删除文档</td><td>&#10003;</td><td>&#10003;（自己的）</td><td>&#10003;（自己的）</td><td>&#10007;</td></tr><tr><td>创建分类</td><td>&#10003;</td><td>&#10003;</td><td>&#10007;</td><td>&#10007;</td></tr><tr><td>管理分类访问</td><td>&#10003;</td><td>&#10003;</td><td>&#10007;</td><td>&#10007;</td></tr><tr><td>运行 AI 搜索</td><td>&#10003;</td><td>&#10003;</td><td>&#10003;</td><td>&#10003;</td></tr><tr><td>共享文档</td><td>&#10003;</td><td>&#10003;</td><td>&#10003;</td><td>&#10007;</td></tr><tr><td>邀请用户</td><td>&#10003;</td><td>&#10007;</td><td>&#10007;</td><td>&#10007;</td></tr><tr><td>管理角色</td><td>&#10003;</td><td>&#10007;</td><td>&#10007;</td><td>&#10007;</td></tr><tr><td>查看审计日志</td><td>&#10003;</td><td>&#10007;</td><td>&#10007;</td><td>&#10007;</td></tr><tr><td>系统设置</td><td>&#10003;</td><td>&#10007;</td><td>&#10007;</td><td>&#10007;</td></tr></tbody></table>' },
  'admin-perm-category': { cat: 'permissions', title: '分类级访问控制', exc: '如何为个别用户授予或限制对特定分类的访问。', body: '<p>除平台范围的角色外，您可以控制哪些用户可以访问每个分类。</p><h2>授予访问权限</h2><ol><li>进入<strong>用户与部门</strong>。</li><li>找到该用户，点击操作列中的<strong>三点图标（&hellip;）</strong>。</li><li>点击<strong>编辑</strong>。</li><li>在<strong>安全与访问配置</strong>部分，勾选<strong>全局访问</strong>。</li><li>点击<strong>保存</strong>以保存更改。</li></ol><div class="tip"><strong>🎬 观看演示：</strong> 观看如何为组织中的用户授予全局访问权限。<div class="video-embed"><a href="https://youtu.be/kzPm6G0zEfQ" target="_blank" rel="noopener noreferrer"><img src="https://img.youtube.com/vi/kzPm6G0zEfQ/hqdefault.jpg" alt="Watch tutorial on YouTube" class="video-thumb small-thumb"><div class="play-overlay">▶</div></a></div></div>' },
  'admin-settings': { cat: 'system-config', title: '系统设置', exc: '配置组织名称、默认语言和通知偏好。', body: '<p>系统设置让您配置 Doc-Scribe.ai 实例的全局行为。</p><h2>全局访问用户</h2><p>全局访问用户可以查看整个组织中的所有文件、分类和部门，无论部门分配如何。</p><p>此访问级别通常授予：</p><ul><li>高级管理层或高管</li><li>IT 管理员</li><li>合规或审计人员</li></ul><p>要添加全局访问用户，点击<strong>添加全局访问用户</strong>并从列表中选择用户。</p><div class="warning"><strong>⚠️ 注意：</strong>请谨慎分配全局访问权限。拥有此权限的用户可以查看所有部门的所有文档，包括敏感文件。</div><h2>回收站保留</h2><p><strong>30 天后自动删除回收站中的文件</strong></p><p>启用此设置后，移至回收站的文件将在 30 天后永久删除。回收站中的文件在永久删除之前仍会计入组织的存储配额。</p><p>启用此设置可在无需手动清理的情况下控制存储使用量。</p><img src="../images/admin setting.png" alt="管理员设置" class="screenshot">' },
  'admin-audit-view': { cat: 'audit-logs', title: '查看审计日志', exc: '如何监控用户活动并筛选审计日志条目。', body: '<p>审计日志记录所有重要的平台操作，包括文档访问、上传、删除、共享和用户管理更改。</p><h2>访问审计日志</h2><p>切换到<strong>用户模式</strong>，然后前往<strong>审计追踪</strong>。</p><h2>记录的内容</h2><ul><li>文档上传、下载、删除或共享</li><li>AI 搜索会话启动</li><li>用户受邀、角色更改、停用或移除</li><li>分类创建、修改或删除</li><li>系统设置更改</li><li>登录和登出事件</li></ul><h2>筛选</h2><p>使用筛选栏按<strong>文件</strong>、<strong>部门</strong>、<strong>用户</strong>或<strong>设置</strong>事件缩小结果范围。</p><ol><li>从左侧导航面板打开<strong>审计追踪</strong>。</li><li>在搜索栏中输入关键词以查找特定活动。</li><li>从下拉菜单中选择事件类型，按所需操作类别筛选结果。</li></ol><img src="../images/admin audit trail.png" alt="Admin Audit Trail" class="screenshot">' },
  'admin-reset-password': { cat: 'user-management', title: '如何重置密码', exc: '使用忘记密码链接重置密码的分步指南。', body: '<p>如果您忘记了密码，请按照以下步骤重置并重新访问您的账户。</p><h2>如何重置密码</h2><ol><li><strong>点击「忘记密码？」</strong><br>在登录页面，点击密码栏上方的 <strong>Forgot Password?</strong> 链接。<img class="screenshot" src="../images/reset-pw-step1.png" alt="登录页面 — 点击忘记密码"></li><li><strong>输入您的电子邮件地址</strong><br>输入您注册的电子邮件地址，然后点击 <strong>Send Verification Code</strong>。<img class="screenshot" src="../images/reset-pw-step2.png" alt="输入电子邮件地址"></li><li><strong>查看您的电子邮件</strong><br>您将收到一封包含 <strong>6位授权码</strong> 的电子邮件。请尽快使用，因为它很快就会过期。<img class="screenshot" src="../images/reset-pw-step3.png" alt="查看电子邮件获取授权码"></li><li><strong>输入验证码并设置新密码</strong><br>输入6位验证码，然后输入新密码。<img class="screenshot" src="../images/reset-pw-step4.png" alt="输入验证码并设置新密码">它必须满足以下要求：<ul><li>至少8个字符</li><li>大写字母 (A&ndash;Z)</li><li>小写字母 (a&ndash;z)</li><li>数字 (0&ndash;9)</li><li>特殊字符 (!@#$%^&amp;*)</li></ul>完成后点击 <strong>Reset Password</strong>。</li><li><strong>密码重置成功！</strong><br>完成！点击 <strong>Back to Sign In</strong>，使用新密码登录。<img class="screenshot" src="../images/reset-pw-step5.png" alt="密码重置成功"></li></ol><div class="tip"><strong>安全提示：</strong>使用强且独特的密码。您的授权码很快就会过期 &mdash; 请在一次会话中完成重置。</div>' },

  'admin-audit-export': { cat: 'audit-logs', title: '导出审计报告', exc: '如何导出审计日志数据用于合规和报告目的。', body: '<p>审计日志可导出为 CSV，用于外部报告、合规审计或与 SIEM 工具集成。</p><h2>导出步骤</h2><ol><li>进入<strong>审计追踪</strong>。</li><li>应用筛选条件（日期范围、用户、操作类型）以确定导出范围。</li><li>点击<strong>导出</strong>。</li><li>文件立即下载到浏览器。</li></ol>' },
};

window.VIDEOS = [
  { id: 'ak2UWuSw_D0', label: '产品概述', title: '产品概述', desc: 'Doc-Scribe.ai 全面概述 — 了解它如何读取、理解文档并采取行动，消除手动数据录入。', thumb: '../images/Thumbnail Product Overview.png', url: 'https://youtu.be/ak2UWuSw_D0' },
  { id: 'UmLDcJ7pvK4', label: '管理员教程 — 初始设置', title: '管理员入门指南', desc: 'Doc-Scribe.ai 平台全面介绍 — 从文档摄取到 AI 驱动的提取与工作流触发。', thumb: '../images/gettingstarted.png', url: 'https://youtu.be/UmLDcJ7pvK4' },
  { id: 'WtNTT6OnOyk', label: '管理员教程 — 管理', title: '安全性与架构', desc: '深入了解 Doc-Scribe.ai 的安全模型、数据架构与部署注意事项。', thumb: '../images/docscribe_structure.png', url: 'https://youtu.be/WtNTT6OnOyk' }
];
