// Admin Portal — 简体中文
// 在 ../data-zh.js 之后加载；仅覆盖 window.CATS 和 window.ARTS。

window.CATS = [
  { id: 'user-management', title: '用户管理', bg: '#eff6ff', fg: '#1d4ed8', desc: '邀请、管理和移除组织中的用户。', arts: ['admin-add-user', 'admin-roles', 'admin-deactivate'], icon: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M23 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/></svg>' },
  { id: 'permissions', title: '权限与角色', bg: '#f0fdf4', fg: '#15803d', desc: '配置每个用户角色可以访问和执行的操作。', arts: ['admin-perm-overview', 'admin-perm-category', 'admin-global-access'], icon: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><rect x="3" y="11" width="18" height="11" rx="2"/><path d="M7 11V7a5 5 0 0 1 10 0v4"/></svg>' },
  { id: 'category-mgmt', title: '分类管理', bg: '#fdf4ff', fg: '#7e22ce', desc: '创建、整理和控制对部门分类的访问。', arts: ['admin-cat-create', 'admin-cat-access'], icon: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M22 19a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5l2 3h9a2 2 0 0 1 2 2z"/></svg>' },
  { id: 'system-config', title: '系统配置', bg: '#fff7ed', fg: '#c2410c', desc: '管理平台设置、文件标签和组织偏好。', arts: ['admin-settings', 'admin-file-tags'], icon: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M12 20h9"/><path d="M16.5 3.5a2.121 2.121 0 0 1 3 3L7 19l-4 1 1-4 12.5-12.5z"/></svg>' },
  { id: 'audit-logs', title: '审计与活动日志', bg: '#fef2f2', fg: '#b91c1c', desc: '监控用户活动并生成合规报告。', arts: ['admin-audit-view', 'admin-audit-export'], icon: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="16" y1="13" x2="8" y2="13"/><line x1="16" y1="17" x2="8" y2="17"/><polyline points="10 9 9 9 8 9"/></svg>' },
];

window.ARTS = {
  'admin-add-user': { cat: 'user-management', title: '邀请和添加用户', exc: '如何邀请新用户并管理待处理的邀请。', body: '<p>作为管理员，您可以直接从管理面板邀请新用户加入您的 Doc-Scribe.ai 组织。</p><h2>邀请用户步骤</h2><ol><li>进入<strong>管理员 &rsaquo; 用户</strong>。</li><li>点击<strong>+ 邀请用户</strong>。</li><li>输入用户的邮箱地址。</li><li>选择角色：管理员、分类管理员、标准用户或只读。</li><li>点击<strong>发送邀请</strong>。</li></ol><p>用户将收到包含邀请链接的邮件，有效期为 <strong>72 小时</strong>。</p><h2>管理待处理邀请</h2><ul><li><strong>重新发送</strong> —— 如果用户未收到邮件。</li><li><strong>取消</strong> —— 在用户加入前撤销访问权限。</li></ul><div class="tip"><strong>提示：</strong>发送前请仔细核对邮箱地址 —— 邀请发出后无法编辑。</div>' },
  'admin-roles': { cat: 'user-management', title: '分配用户角色', exc: '如何更改用户在平台中的角色。', body: '<p>用户角色决定其可执行的操作，管理员可随时更改。</p><h2>可用角色</h2><table><thead><tr><th>角色</th><th>描述</th></tr></thead><tbody><tr><td><strong>管理员</strong></td><td>完整控制 —— 用户、分类、设置、审计日志。</td></tr><tr><td><strong>分类管理员</strong></td><td>可创建和管理分类；不能管理用户或系统设置。</td></tr><tr><td><strong>标准用户</strong></td><td>可上传、整理并对可访问文档运行 AI 搜索。</td></tr><tr><td><strong>只读</strong></td><td>只能查看和对共享文档使用 AI 搜索。</td></tr></tbody></table><h2>更改角色</h2><ol><li>进入<strong>管理员 &rsaquo; 用户</strong>。</li><li>点击用户姓名。</li><li>点击<strong>编辑角色</strong>，选择新角色并确认。</li></ol><p>角色变更立即生效，无需重新登录。</p>' },
  'admin-deactivate': { cat: 'user-management', title: '停用和移除用户', exc: '如何暂停或永久移除组织中的用户。', body: '<p>当用户离开或需要暂停访问时，您可以停用或移除其账户。</p><h2>停用用户（推荐）</h2><p>停用暂停访问同时保留所有文档和历史记录，可随时重新激活。</p><ol><li>进入<strong>管理员 &rsaquo; 用户</strong>。</li><li>点击用户姓名。</li><li>点击<strong>停用用户</strong>并确认。</li></ol><h2>永久移除用户</h2><p>永久移除将删除账户，My Box 中的文档将被归档。</p><ol><li>进入<strong>管理员 &rsaquo; 用户</strong>。</li><li>点击用户姓名。</li><li>点击<strong>移除用户</strong>并确认。</li></ol><div class="tip"><strong>注意：</strong>永久移除无法撤销。建议使用停用，除非出于合规原因需要清除数据。</div>' },
  'admin-perm-overview': { cat: 'permissions', title: '权限概述', exc: '每个用户角色能做和不能做的事情的完整分解。', body: '<p>下表总结了平台各功能的权限。</p><table><thead><tr><th>功能</th><th>管理员</th><th>分类管理员</th><th>标准</th><th>只读</th></tr></thead><tbody><tr><td>上传文档</td><td>&#10003;</td><td>&#10003;</td><td>&#10003;</td><td>&#10007;</td></tr><tr><td>删除文档</td><td>&#10003;</td><td>&#10003;（自己的）</td><td>&#10003;（自己的）</td><td>&#10007;</td></tr><tr><td>创建分类</td><td>&#10003;</td><td>&#10003;</td><td>&#10007;</td><td>&#10007;</td></tr><tr><td>管理分类访问</td><td>&#10003;</td><td>&#10003;</td><td>&#10007;</td><td>&#10007;</td></tr><tr><td>运行 AI 搜索</td><td>&#10003;</td><td>&#10003;</td><td>&#10003;</td><td>&#10003;</td></tr><tr><td>共享文档</td><td>&#10003;</td><td>&#10003;</td><td>&#10003;</td><td>&#10007;</td></tr><tr><td>邀请用户</td><td>&#10003;</td><td>&#10007;</td><td>&#10007;</td><td>&#10007;</td></tr><tr><td>管理角色</td><td>&#10003;</td><td>&#10007;</td><td>&#10007;</td><td>&#10007;</td></tr><tr><td>查看审计日志</td><td>&#10003;</td><td>&#10007;</td><td>&#10007;</td><td>&#10007;</td></tr><tr><td>系统设置</td><td>&#10003;</td><td>&#10007;</td><td>&#10007;</td><td>&#10007;</td></tr></tbody></table>' },
  'admin-perm-category': { cat: 'permissions', title: '分类级访问控制', exc: '如何为个别用户授予或限制对特定分类的访问。', body: '<p>除平台范围的角色外，您可以控制哪些用户可以访问每个分类。</p><h2>授予访问权限</h2><ol><li>进入<strong>管理员 &rsaquo; 分类</strong>，点击分类名称。</li><li>在<em>访问控制</em>下，点击<strong>+ 添加用户</strong>。</li><li>按姓名或邮箱搜索，选择访问级别：<em>仅查看</em>或<em>查看并上传</em>。</li><li>点击<strong>保存</strong>。</li></ol><h2>撤销访问权限</h2><ol><li>在管理员 &rsaquo; 分类中打开分类。</li><li>在访问控制下找到用户，点击其姓名旁的<strong>移除</strong>。</li></ol><div class="tip"><strong>注意：</strong>无论分类级别设置如何，管理员始终对所有分类拥有访问权限。</div>' },
  'admin-global-access': { cat: 'permissions', title: '全局访问', exc: '如何使文档或分类对组织中所有用户可访问。', body: '<p>全局访问允许组织中的任何用户访问特定文档或分类，无需单独共享。</p><h2>在文档上启用</h2><ol><li>打开文档，点击<strong>共享</strong>。</li><li>将<strong>全局访问</strong>切换为开启。</li><li>选择<em>可查看</em>或<em>可下载</em>。</li><li>点击<strong>保存</strong>。</li></ol><h2>在分类上启用</h2><ol><li>进入<strong>管理员 &rsaquo; 分类</strong>，点击分类。</li><li>在访问控制下，启用<strong>全局访问</strong>。</li></ol><p>将全局访问用于公司政策、标准操作程序和共享模板。</p><div class="tip"><strong>最佳实践：</strong>谨慎使用全局访问。对于敏感文档，请始终使用基于个人或角色的共享。</div>' },
  'admin-cat-create': { cat: 'category-mgmt', title: '创建和管理分类', exc: '如何创建新的部门分类并配置其设置。', body: '<p>分类是共享的部门级文件夹，团队成员可根据权限访问。</p><h2>创建分类</h2><ol><li>进入<strong>管理员 &rsaquo; 分类</strong>。</li><li>点击<strong>+ 新分类</strong>。</li><li>输入名称和可选描述。</li><li>点击<strong>创建</strong>。</li></ol><h2>编辑分类</h2><ol><li>点击分类名称。</li><li>点击<strong>编辑</strong>，更新名称或描述，然后保存。</li></ol><h2>删除分类</h2><ol><li>点击分类名称。</li><li>点击<strong>删除分类</strong>并确认。</li></ol><div class="tip"><strong>警告：</strong>删除分类会将其中所有文档移至归档状态。文档不会被永久删除，但在管理员恢复之前不会出现在标准视图中。</div>' },
  'admin-cat-access': { cat: 'category-mgmt', title: '管理分类成员', exc: '如何添加或移除分类用户并设置其访问级别。', body: '<p>每个分类都有独立的访问控制列表，您可以单独管理。</p><h2>添加成员</h2><ol><li>进入<strong>管理员 &rsaquo; 分类</strong>，点击分类。</li><li>在<em>成员</em>下，点击<strong>+ 添加成员</strong>。</li><li>按姓名或邮箱搜索并选择用户。</li><li>选择：<em>仅查看</em>或<em>贡献者</em>（也可上传和整理）。</li><li>点击<strong>添加</strong>。</li></ol><h2>移除成员</h2><ol><li>在管理员 &rsaquo; 分类中打开分类。</li><li>在成员下找到用户，点击<strong>移除</strong>。</li></ol><p>更改在受影响用户下次加载页面时立即生效。</p>' },
  'admin-settings': { cat: 'system-config', title: '系统设置', exc: '配置组织名称、默认语言和通知偏好。', body: '<p>系统设置让您配置 Doc-Scribe.ai 实例的全局行为。</p><h2>访问设置</h2><p>进入<strong>管理员 &rsaquo; 设置</strong>。</p><h2>组织设置</h2><ul><li><strong>组织名称</strong> —— 显示在平台页眉和邮件通知中。</li><li><strong>默认语言</strong> —— 为新用户设置默认界面语言。</li><li><strong>时区</strong> —— 用于审计日志和通知时间戳。</li></ul><h2>通知设置</h2><ul><li><strong>文档共享</strong> —— 当文档与用户共享时通知用户。</li><li><strong>邀请接受</strong> —— 当受邀用户加入时通知管理员。</li><li><strong>存储阈值</strong> —— 当存储使用量超过设定限制时提醒管理员。</li></ul><p>进行任何更改后，点击<strong>保存设置</strong>。</p>' },
  'admin-file-tags': { cat: 'system-config', title: '文件标签管理', exc: '如何创建和管理文档的自定义元数据字段。', body: '<p>文件标签是出现在每个文档上的自定义元数据字段，帮助用户使用结构化数据对文档进行分类和搜索。</p><h2>创建文件标签</h2><ol><li>进入<strong>管理员 &rsaquo; 设置 &rsaquo; 文件标签</strong>。</li><li>点击<strong>+ 新标签</strong>。</li><li>输入标签名称（例如：<em>部门</em>、<em>合同日期</em>、<em>客户</em>）。</li><li>选择类型：文本、日期、下拉菜单或数字。</li><li>设置字段是<em>必填</em>还是<em>可选</em>。</li><li>点击<strong>保存</strong>。</li></ol><h2>编辑和删除标签</h2><p>您可以从管理员 &rsaquo; 设置 &rsaquo; 文件标签重命名或删除标签。删除标签会将其从所有文档中移除 —— 现有值将丢失。</p><div class="tip"><strong>提示：</strong>目标是 5–8 个基本字段。标签过多会给上传文档的用户造成阻碍。</div>' },
  'admin-audit-view': { cat: 'audit-logs', title: '查看审计日志', exc: '如何监控用户活动并筛选审计日志条目。', body: '<p>审计日志记录所有重要的平台操作，包括文档访问、上传、删除、共享和用户管理更改。</p><h2>访问审计日志</h2><p>进入<strong>管理员 &rsaquo; 审计日志</strong>。</p><h2>记录的内容</h2><ul><li>文档上传、下载、删除或共享</li><li>AI 搜索会话启动</li><li>用户受邀、角色更改、停用或移除</li><li>分类创建、修改或删除</li><li>系统设置更改</li><li>登录和登出事件</li></ul><h2>筛选</h2><p>使用日志顶部的筛选栏按<strong>用户</strong>、<strong>操作类型</strong>、<strong>日期范围</strong>或<strong>文档</strong>筛选。</p>' },
  'admin-audit-export': { cat: 'audit-logs', title: '导出审计报告', exc: '如何导出审计日志数据用于合规和报告目的。', body: '<p>审计日志可导出为 CSV，用于外部报告、合规审计或与 SIEM 工具集成。</p><h2>导出步骤</h2><ol><li>进入<strong>管理员 &rsaquo; 审计日志</strong>。</li><li>应用筛选条件（日期范围、用户、操作类型）以确定导出范围。</li><li>点击<strong>导出 CSV</strong>。</li><li>文件立即下载到浏览器。</li></ol><h2>CSV 包含的字段</h2><ul><li>时间戳（ISO 8601）</li><li>用户姓名和邮箱</li><li>操作类型</li><li>资源名称（文档或分类）</li><li>IP 地址</li><li>结果（成功 / 失败）</li></ul><div class="tip"><strong>合规说明：</strong>对于 GDPR 或 PDPA 审计要求，请导出涵盖相关期间的日志，并按照组织的数据保留政策进行保存。</div>' },
};

window.VIDEOS = [
  { id: 'UmLDcJ7pvK4', label: '管理员教程 — 初始设置', title: '管理员入门指南', desc: '完整演示管理员面板，包括邀请用户、分配角色与配置系统设置。', thumb: 'https://img.youtube.com/vi/UmLDcJ7pvK4/maxresdefault.jpg', url: 'https://youtu.be/UmLDcJ7pvK4' },
  { id: 'WtNTT6OnOyk', label: '管理员教程 — 管理', title: '用户、权限与审计日志管理', desc: '配置类别访问、管理角色与导出合规报告。', thumb: 'https://img.youtube.com/vi/WtNTT6OnOyk/maxresdefault.jpg', url: 'https://youtu.be/WtNTT6OnOyk' }
];
